server:
  port: 8082

spring:
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update
    show-sql: true

  application:
    name: HOTEL_SERVICE

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/hotelservice
  username: postgres
  password: postgres


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

